import 'package:annix/global.dart';
import 'package:annix/services/font.dart';
import 'package:flutter/material.dart';

class AnnixTheme extends ChangeNotifier {
  AnnixTheme()
      : _primaryColor = Colors.indigo,
        _primaryScheme = ColorScheme.fromSeed(seedColor: Colors.indigo),
        _primaryDarkScheme = ColorScheme.fromSeed(
            seedColor: Colors.indigo, brightness: Brightness.dark),
        _themeMode = ThemeMode.system;

  // main theme generated by now-playing cover
  Color _primaryColor;
  ColorScheme _primaryScheme;
  ColorScheme _primaryDarkScheme;

  // temporary theme generated per-page
  Color? _temporaryPrimaryColor;
  ColorScheme? _temporaryPrimaryScheme;
  ColorScheme? _temporaryPrimaryDarkScheme;

  ThemeData get theme => ThemeData(
        useMaterial3: true,
        brightness: Brightness.light,
        fontFamily: FontService.getFontFamilyName(),
        colorScheme: _temporaryPrimaryScheme ?? _primaryScheme,
      );
  ThemeData get darkTheme => ThemeData(
        useMaterial3: true,
        brightness: Brightness.dark,
        fontFamily: FontService.getFontFamilyName(),
        colorScheme: _temporaryPrimaryDarkScheme ?? _primaryDarkScheme,
      );

  ThemeMode _themeMode;
  ThemeMode get themeMode => _themeMode;

  void setTemporaryScheme(final ColorScheme scheme, final ColorScheme darkScheme) {
    _temporaryPrimaryColor = scheme.primary;
    _temporaryPrimaryScheme = scheme;
    _temporaryPrimaryDarkScheme = darkScheme;
    notifyListeners();
  }

  void revokeTemporaryScheme() {
    if (_temporaryPrimaryColor != null) {
      final oldTemporaryPrimaryColor = _temporaryPrimaryColor;
      _temporaryPrimaryColor = null;
      _temporaryPrimaryScheme = null;
      _temporaryPrimaryDarkScheme = null;

      if (oldTemporaryPrimaryColor != _primaryColor) {
        notifyListeners();
      }
    }
  }

  void setScheme(final ColorScheme scheme, final ColorScheme darkScheme) {
    _primaryColor = scheme.primary;
    _primaryScheme = scheme;
    _primaryDarkScheme = darkScheme;
    notifyListeners();
  }

  void setThemeMode(final ThemeMode mode) {
    if (mode != _themeMode) {
      _themeMode = mode;
      notifyListeners();
    }
  }

  void updateFontFamily() {
    notifyListeners();
  }
}

class ThemePopObserver extends NavigatorObserver {
  @override
  didPop(final Route<dynamic> route, final Route<dynamic>? previousRoute) {
    WidgetsBinding.instance.addPostFrameCallback((final _) {
      Global.theme.revokeTemporaryScheme();
    });
  }
}
