// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.81.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

abstract class AnnixNative {
  Future<void> updateNetworkStatus({required bool isOnline, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kUpdateNetworkStatusConstMeta;

  Future<bool> isOnlineMethodNetworkStatus({required NetworkStatus that, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kIsOnlineMethodNetworkStatusConstMeta;

  NativePreferenceStore newStaticMethodNativePreferenceStore({required String root, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kNewStaticMethodNativePreferenceStoreConstMeta;

  String? getMethodNativePreferenceStore({required NativePreferenceStore that, required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetMethodNativePreferenceStoreConstMeta;

  void setMethodNativePreferenceStore(
      {required NativePreferenceStore that, required String key, required String value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSetMethodNativePreferenceStoreConstMeta;

  void removeMethodNativePreferenceStore({required NativePreferenceStore that, required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kRemoveMethodNativePreferenceStoreConstMeta;

  void removePrefixMethodNativePreferenceStore(
      {required NativePreferenceStore that, required String prefix, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kRemovePrefixMethodNativePreferenceStoreConstMeta;

  Future<LocalDb> newStaticMethodLocalDb({required String path, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kNewStaticMethodLocalDbConstMeta;

  Future<String?> getAlbumMethodLocalDb({required LocalDb that, required UuidValue albumId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetAlbumMethodLocalDbConstMeta;

  Future<List<UuidValue>> getAlbumsByTagMethodLocalDb(
      {required LocalDb that, required String tag, required bool recursive, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetAlbumsByTagMethodLocalDbConstMeta;

  Future<List<TagItem>> getTagsMethodLocalDb({required LocalDb that, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetTagsMethodLocalDbConstMeta;

  LocalStore newStaticMethodLocalStore({required String root, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kNewStaticMethodLocalStoreConstMeta;

  Future<void> insertMethodLocalStore(
      {required LocalStore that, required String category, required String key, required String value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kInsertMethodLocalStoreConstMeta;

  Future<String?> getMethodLocalStore(
      {required LocalStore that, required String category, required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetMethodLocalStoreConstMeta;

  Future<void> clearMethodLocalStore({required LocalStore that, String? category, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kClearMethodLocalStoreConstMeta;

  DropFnType get dropOpaqueMutexConnection;
  ShareFnType get shareOpaqueMutexConnection;
  OpaqueTypeFinalizer get MutexConnectionFinalizer;

  DropFnType get dropOpaqueMutexDummy1Connection;
  ShareFnType get shareOpaqueMutexDummy1Connection;
  OpaqueTypeFinalizer get MutexDummy1ConnectionFinalizer;

  DropFnType get dropOpaqueMutexRepoDatabaseRead;
  ShareFnType get shareOpaqueMutexRepoDatabaseRead;
  OpaqueTypeFinalizer get MutexRepoDatabaseReadFinalizer;
}

@sealed
class MutexConnection extends FrbOpaque {
  final AnnixNative bridge;
  MutexConnection.fromRaw(int ptr, int size, this.bridge) : super.unsafe(ptr, size);
  @override
  DropFnType get dropFn => bridge.dropOpaqueMutexConnection;

  @override
  ShareFnType get shareFn => bridge.shareOpaqueMutexConnection;

  @override
  OpaqueTypeFinalizer get staticFinalizer => bridge.MutexConnectionFinalizer;
}

@sealed
class MutexDummy1Connection extends FrbOpaque {
  final AnnixNative bridge;
  MutexDummy1Connection.fromRaw(int ptr, int size, this.bridge) : super.unsafe(ptr, size);
  @override
  DropFnType get dropFn => bridge.dropOpaqueMutexDummy1Connection;

  @override
  ShareFnType get shareFn => bridge.shareOpaqueMutexDummy1Connection;

  @override
  OpaqueTypeFinalizer get staticFinalizer => bridge.MutexDummy1ConnectionFinalizer;
}

@sealed
class MutexRepoDatabaseRead extends FrbOpaque {
  final AnnixNative bridge;
  MutexRepoDatabaseRead.fromRaw(int ptr, int size, this.bridge) : super.unsafe(ptr, size);
  @override
  DropFnType get dropFn => bridge.dropOpaqueMutexRepoDatabaseRead;

  @override
  ShareFnType get shareFn => bridge.shareOpaqueMutexRepoDatabaseRead;

  @override
  OpaqueTypeFinalizer get staticFinalizer => bridge.MutexRepoDatabaseReadFinalizer;
}

/// Repo
class LocalDb {
  final AnnixNative bridge;
  final MutexRepoDatabaseRead repo;

  const LocalDb({
    required this.bridge,
    required this.repo,
  });

  static Future<LocalDb> newLocalDb({required AnnixNative bridge, required String path, dynamic hint}) =>
      bridge.newStaticMethodLocalDb(path: path, hint: hint);

  Future<String?> getAlbum({required UuidValue albumId, dynamic hint}) => bridge.getAlbumMethodLocalDb(
        that: this,
        albumId: albumId,
      );

  Future<List<UuidValue>> getAlbumsByTag({required String tag, required bool recursive, dynamic hint}) =>
      bridge.getAlbumsByTagMethodLocalDb(
        that: this,
        tag: tag,
        recursive: recursive,
      );

  Future<List<TagItem>> getTags({dynamic hint}) => bridge.getTagsMethodLocalDb(
        that: this,
      );
}

class LocalStore {
  final AnnixNative bridge;
  final MutexConnection conn;

  const LocalStore({
    required this.bridge,
    required this.conn,
  });

  static LocalStore newLocalStore({required AnnixNative bridge, required String root, dynamic hint}) =>
      bridge.newStaticMethodLocalStore(root: root, hint: hint);

  Future<void> insert({required String category, required String key, required String value, dynamic hint}) =>
      bridge.insertMethodLocalStore(
        that: this,
        category: category,
        key: key,
        value: value,
      );

  Future<String?> get({required String category, required String key, dynamic hint}) => bridge.getMethodLocalStore(
        that: this,
        category: category,
        key: key,
      );

  Future<void> clear({String? category, dynamic hint}) => bridge.clearMethodLocalStore(
        that: this,
        category: category,
      );
}

class NativePreferenceStore {
  final AnnixNative bridge;
  final MutexDummy1Connection conn;

  const NativePreferenceStore({
    required this.bridge,
    required this.conn,
  });

  static NativePreferenceStore newNativePreferenceStore(
          {required AnnixNative bridge, required String root, dynamic hint}) =>
      bridge.newStaticMethodNativePreferenceStore(root: root, hint: hint);

  String? get({required String key, dynamic hint}) => bridge.getMethodNativePreferenceStore(
        that: this,
        key: key,
      );

  void set({required String key, required String value, dynamic hint}) => bridge.setMethodNativePreferenceStore(
        that: this,
        key: key,
        value: value,
      );

  void remove({required String key, dynamic hint}) => bridge.removeMethodNativePreferenceStore(
        that: this,
        key: key,
      );

  void removePrefix({required String prefix, dynamic hint}) => bridge.removePrefixMethodNativePreferenceStore(
        that: this,
        prefix: prefix,
      );
}

enum NetworkStatus {
  online,
  offline,
}

class TagItem {
  final String name;
  final List<String> children;

  const TagItem({
    required this.name,
    required this.children,
  });
}
