// This file initializes the dynamic library and connects it with the stub
// generated by flutter_rust_bridge_codegen.

import 'dart:ffi';

import 'package:annix/bridge/bridge_generated.dart';
export 'package:annix/bridge/bridge_generated.dart';
export 'package:annix/bridge/bridge_definitions.dart';

// Re-export the bridge so it is only necessary to import this file.
import 'dart:io' as io;

const _base = 'annix_native';

// On MacOS, the dynamic library is not bundled with the binary,
// but rather directly **linked** against the binary.
final _dylibPath = io.Platform.isWindows ? '$_base.dll' : 'lib$_base.so';
final _dylib = io.Platform.isIOS || io.Platform.isMacOS
    ? DynamicLibrary.executable()
    : DynamicLibrary.open(_dylibPath);

final api = AnnixNativeImpl(_dylib);
