rust_input:
  - src/api.rs
rust_output:
  - src/bridge_generated.rs

dart_output:
  - ../lib/bridge/bridge_generated.dart
c_output:
  - ../ios/Runner/bridge_generated.h
extra_c_output_path:
  - ../macos/Runner/

dart_decl_output: ../lib/bridge/bridge_definitions.dart
dart_format_line_length: 120
dart_enums_style: true
# dump: []
skip_add_mod_to_lib: true
wasm: false