[package]
name = "annix-native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
flutter_rust_bridge = "1"

# Color
image = "0.24.5"
material-color-utilities-rs = "0.2.1"
