[package]
name = "annix-native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
flutter_rust_bridge = "1"
once_cell = "1.17.1"
rusqlite = { version = "0.28.0", features = ["bundled"] }
