// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> updateNetworkStatus({required bool isOnline}) =>
    RustLib.instance.api.crateApiNetworkUpdateNetworkStatus(isOnline: isOnline);

enum NetworkStatus {
  online,
  offline,
  ;

  Future<bool> isOnline() =>
      RustLib.instance.api.crateApiNetworkNetworkStatusIsOnline(
        that: this,
      );
}
