// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.32.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> updateNetworkStatus({required bool isOnline, dynamic hint}) =>
    RustLib.instance.api.updateNetworkStatus(isOnline: isOnline, hint: hint);

enum NetworkStatus {
  online,
  offline,
  ;

  Future<bool> isOnline({dynamic hint}) =>
      RustLib.instance.api.networkStatusIsOnline(that: this, hint: hint);
}
