// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGdDybX7Nt1dABMJTMNWxYCyya5m0MVqY',
    appId: '1:155003412918:android:a74c0164cad2e2ac376117',
    messagingSenderId: '155003412918',
    projectId: 'project-anni-firebase',
    storageBucket: 'project-anni-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPtL7sXBERbvkfpyzpFsEoVPeTZemEWnA',
    appId: '1:155003412918:ios:015e4bb181171702376117',
    messagingSenderId: '155003412918',
    projectId: 'project-anni-firebase',
    storageBucket: 'project-anni-firebase.appspot.com',
    iosBundleId: 'rs.anni.annix.debug',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPtL7sXBERbvkfpyzpFsEoVPeTZemEWnA',
    appId: '1:155003412918:ios:997285e685ed1b22376117',
    messagingSenderId: '155003412918',
    projectId: 'project-anni-firebase',
    storageBucket: 'project-anni-firebase.appspot.com',
    iosBundleId: 'rs.anni.annix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvdR-i0SHai-suzw3NhmMz7PEV0YlynpA',
    appId: '1:155003412918:web:0ef56365e8434cd4376117',
    messagingSenderId: '155003412918',
    projectId: 'project-anni-firebase',
    authDomain: 'project-anni-firebase.firebaseapp.com',
    storageBucket: 'project-anni-firebase.appspot.com',
    measurementId: 'G-TCHGH4GL6F',
  );

}