[package]
name = "rust_lib_annix"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = { version = "=2.1.0", features = ["uuid"] }

once_cell = "1.17.1"
rusqlite = { version = "0.28.0", features = ["bundled"] }

anni-repo = { version = "0.4.1", features = ["db"] }
uuid = "1"
crossbeam = { version = "0.8.2", features = ["crossbeam-channel"] }
anyhow = "1.0.75"
log = "0.4.20"

anni-playback = { git = "https://github.com/ProjectAnni/anni" }
cpal = { version = "0.15.3", features = ["oboe-shared-stdcxx"] }
rand = "0.8.5"
material-colors = { version = "0.3.3", features = ["image"] }
