[package]
name = "rust_lib_annix"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = { version = "=2.1.0", features = ["uuid"] }

once_cell = "1.17.1"
rusqlite = { version = "0.30.0", features = ["bundled"] }

anni-repo = { version = "0.4.2", features = ["db"] }
uuid = "1"
crossbeam = { version = "0.8.2", features = ["crossbeam-channel"] }
anyhow = "1.0.75"
log = "0.4.20"
env_logger = "0.11"

anni-playback = { git = "https://github.com/ProjectAnni/anni", rev = "616ccbca7e5f7df4c039b103248136c7d32ffe46" }
cpal = { version = "0.15.3", features = ["oboe-shared-stdcxx"] }
rand = "0.8.5"
material-colors = { version = "0.3.3", features = ["image"] }

db_logger = { git = "https://github.com/ProjectAnni/db_logger.git", branch = "upgrade-sqlx", default-features = false, features = [
    "sqlite",
] }
tokio = { version = "1.39.2", features = ["rt-multi-thread"] }

[patch.crates-io]
cpal = { git = "https://github.com/sidit77/cpal.git", branch = "master" }
